/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocol.h"

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->format, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
