/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <time.h>

#include "protocol.h"

    struct result *
getdate_1_svc(void *argp, struct svc_req *rqstp)
{
    static struct result  result;
    time_t rawtime;
    struct tm * timeinfo;

    time(&rawtime);
    timeinfo = localtime (&rawtime);
    strcpy(result.res, asctime(timeinfo));

    return &result;
}
