/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocol.h"

bool_t
xdr_result (XDR *xdrs, result *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->res, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}
