/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROTOCOL_H_RPCGEN
#define _PROTOCOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct result {
	char res[100];
	int len;
};
typedef struct result result;

#define DATETIME 0x2fffffff
#define DATETIME_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETDATE 1
extern  struct result * getdate_1(void *, CLIENT *);
extern  struct result * getdate_1_svc(void *, struct svc_req *);
extern int datetime_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETDATE 1
extern  struct result * getdate_1();
extern  struct result * getdate_1_svc();
extern int datetime_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_result (XDR *, result*);

#else /* K&R C */
extern bool_t xdr_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROTOCOL_H_RPCGEN */
